# Generated by Django 5.1.4 on 2025-04-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('depression', models.FloatField()),
                ('anxiety', models.FloatField()),
                ('stress', models.FloatField()),
            ],
            options={
                'db_table': 'audio_result',
            },
        ),
    ]
