# Generated by Django 5.1.4 on 2025-04-06 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depression_score', models.FloatField(blank=True, null=True)),
                ('anxiety_score', models.FloatField(blank=True, null=True)),
                ('stress_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cumulative_depression_score', models.FloatField(blank=True, null=True)),
                ('cumulative_anxiety_score', models.FloatField(blank=True, null=True)),
                ('cumulative_stress_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
