# Generated by Django 5.1.4 on 2025-04-06 07:09

import userauth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('guardian_number', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to=userauth.models.pdf_report_upload_path)),
                ('final_depression', models.FloatField()),
                ('final_anxiety', models.FloatField()),
                ('final_stress', models.FloatField()),
                ('questionnaire_depression', models.FloatField()),
                ('questionnaire_anxiety', models.FloatField()),
                ('questionnaire_stress', models.FloatField()),
                ('audio_depression', models.FloatField()),
                ('audio_anxiety', models.FloatField()),
                ('audio_stress', models.FloatField()),
                ('video_depression', models.FloatField()),
                ('video_anxiety', models.FloatField()),
                ('video_stress', models.FloatField()),
            ],
            options={
                'db_table': 'pdf_report',
                'unique_together': {('email', 'time_stamp')},
            },
        ),
    ]
