# Generated by Django 5.0.2 on 2025-03-22 09:19

import userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_pdfreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfreport',
            name='pdf_file',
            field=models.FileField(upload_to=userauth.models.pdf_report_upload_path),
        ),
    ]
